### ISSUE TITLE
'Authors' tags fail and crash the linter...

### ISSUE THREAD

**Issue by diranged** [petems/puppet-doc-lint#9]
If you add an Authors section to any of the unit tests, the app breaks..

```
diff --git a/spec/manifests/parameters_rdoc.pp b/spec/manifests/parameters_rdoc.pp
index d9f329f..34c940e 100644
--- a/spec/manifests/parameters_rdoc.pp
+++ b/spec/manifests/parameters_rdoc.pp
@@ -10,6 +10,11 @@
 #
 # [*param_one*]
 #    Param1 documentation text
+#
+# == Authors
+#
+# Matt <matt@me.com>
+#
class parameters_rdoc (
   $param_one = true,
   $param_two = '',
```

Broken tests:

```
All examples were filtered out; ignoring {:focus=>true}
.....FFFFFF............F.........................

Failures:

  1) PuppetDocLint::DocRunner manifest with parameters and rdoc it should behave like parameters parameters should have 4 elements spec/manifests/parameters_rdoc.pp
     Failure/Error: subject { setup(file) }
     NoMethodError:
       undefined method `items' for #<RDoc::Markup::Paragraph:0x007fdca53d68d0>
     Shared Example Group: "parameters" called from ./spec/runner_acceptance_spec.rb:82
     # ./lib/puppet-doc-lint/parser.rb:67:in `block in authors'
     # ./lib/puppet-doc-lint/parser.rb:65:in `each'
     # ./lib/puppet-doc-lint/parser.rb:65:in `authors'
     # ./lib/puppet-doc-lint/runner.rb:29:in `block in run'
     # ./lib/puppet-doc-lint/runner.rb:5:in `each'
     # ./lib/puppet-doc-lint/runner.rb:5:in `run'
     # ./spec/runner_acceptance_spec.rb:23:in `block (3 levels) in <top (required)>'
     # ./spec/runner_acceptance_spec.rb:25:in `block (3 levels) in <top (required)>'
```

This happens to any of our puppet manifests with Authors tags in the documentation right now.
